---
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt

formats: all
